'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

const fallback:[string,string,string,string,string][]=[['Belajar dari Dunia Industri','Kegiatan pembelajaran dan kolaborasi siswa yang dekat dengan kebutuhan dunia kerja.','12 Sep 2026','/images/school/hero-lab.jpg','belajar-dari-dunia-industri'],['Aktivitas Siswa Tunas Harapan','Potret aktivitas siswa dalam lingkungan belajar dan kegiatan sekolah.','08 Sep 2026','/images/school/hero-courtyard.jpg','aktivitas-siswa-tunas-harapan'],['Tunas Harapan dan Teknologi','Sekolah terus mengembangkan pengalaman belajar berbasis teknologi dan kompetensi.','02 Sep 2026','/images/school/building-main.png','tunas-harapan-dan-teknologi']];

type BeritaPublik={id:string|number;judul:string;subjudul?:string|null;konten:string;gambar_url?:string|null;created_at?:string|null};

function formatTanggal(iso:string|null|undefined){if(!iso)return '';try{return new Date(iso).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'});}catch{return '';}}
function teksBersih(markdown:string){return (markdown||'').replace(/!\[.*?\]\(.*?\)/g,' ').replace(/\[([^\]]+)\]\(.*?\)/g,'$1').replace(/[#*_>`-]/g,'').replace(/\s+/g,' ').trim();}

export default function Berita(){
const [daftar,setDaftar]=useState<BeritaPublik[]>([]);
const [memuat,setMemuat]=useState(true);
useEffect(()=>{let batal=false;fetch('/api/berita?limit=100').then(r=>r.json()).then(d=>{if(batal)return;if(d?.ok&&Array.isArray(d.data))setDaftar(d.data);}).catch(()=>{}).finally(()=>{if(!batal)setMemuat(false);});return()=>{batal=true;};},[]);
return <main className="min-h-screen bg-[#F4F9FF] px-6 py-24 text-[#021024]"><div className="mx-auto max-w-7xl"><Link href="/" className="text-xs text-[#021024]/45">← Beranda</Link><p className="eyebrow mt-20 text-[#2F5F8F]">BERITA</p><h1 className="mt-5 text-5xl font-semibold tracking-tight sm:text-8xl">Berita terbaru.</h1>{memuat?<div className="mt-16 grid gap-6 md:grid-cols-3">{[0,1,2].map(i=><div key={i} className="animate-pulse overflow-hidden rounded-[1.6rem] bg-white"><div className="aspect-[16/10] bg-[#021024]/10" /><div className="space-y-3 p-6"><div className="h-4 w-2/3 rounded bg-[#021024]/10" /><div className="h-3 w-full rounded bg-[#021024]/10" /></div></div>)}</div>:daftar.length===0?<div className="mt-16 grid gap-6 md:grid-cols-3">{fallback.map(([t,d,date,img,s])=><Link href={`/berita/${s}`} key={s} className="group overflow-hidden rounded-[1.6rem] bg-white"><div className="aspect-[16/10] overflow-hidden"><img src={img} alt="" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-6"><p className="eyebrow text-[#2F5F8F]/60">{date}</p><h2 className="mt-3 text-2xl">{t}</h2><p className="mt-3 text-sm leading-6 text-black/50">{d}</p></div></Link>)}</div>:<div className="mt-16 grid gap-6 md:grid-cols-3">{daftar.map((b)=><Link href={`/berita/${String(b.id)}`} key={String(b.id)} className="group overflow-hidden rounded-[1.6rem] bg-white"><div className="aspect-[16/10] overflow-hidden bg-[#052659]/5">{b.gambar_url?<img src={b.gambar_url} alt="" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/>:<div className="grid h-full w-full place-items-center text-[#052659]/25">Tidak ada gambar</div>}</div><div className="p-6"><p className="eyebrow text-[#2F5F8F]/60">{formatTanggal(b.created_at)||'Baru saja'}</p><h2 className="mt-3 line-clamp-2 text-2xl">{b.judul}</h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-black/50">{b.subjudul||teksBersih(b.konten).slice(0,140)}</p></div></Link>)}</div>}</div></main>}
